//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNCF_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class billet
    {
        public int idbillet { get; set; }
        public string villeDepart { get; set; }
        public string villeArrivee { get; set; }
        public string gareDepart { get; set; }
        public string gareArrivee { get; set; }
        public Nullable<System.DateTime> heureDepart { get; set; }
        public Nullable<System.DateTime> heureArrivee { get; set; }
        public Nullable<float> prix { get; set; }
        public Nullable<int> idtrain { get; set; }
        public Nullable<int> idvoiture { get; set; }
        public Nullable<int> idplace { get; set; }
        public Nullable<int> idclient { get; set; }
    
        public virtual client client { get; set; }
        public virtual place place { get; set; }
        public virtual train train { get; set; }
        public virtual voiture voiture { get; set; }
    }
}
