/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;

namespace SNCF_2
{
	public partial class frmbillet : Form
	{
        private Model3 ctx;
		
		public frmbillet()
		{
			InitializeComponent();
		}
		
		private void frmbillet_Load(object sender, EventArgs e)
		{
            ctx = new Model3();
			ctx.billet.Load();
			BindingList<billet> _entities = ctx.billet.Local.ToBindingList();
			billetBindingSource.DataSource = _entities;
			bindingNavigatorAddNewItem.Enabled = false;
			bindingNavigatorCountItem.Enabled = false;
			bindingNavigatorDeleteItem.Enabled = false;
			bindingNavigatorMoveFirstItem.Enabled = false;
			bindingNavigatorMovePreviousItem.Enabled = false;
			bindingNavigatorPositionItem.Enabled = false;
			bindingNavigatorMoveNextItem.Enabled = false;
			bindingNavigatorMoveLastItem.Enabled = false;
			toolStripButton1.Enabled = true;
			dataGridView1.AutoGenerateColumns = false;
			string strConn2 = "server=localhost;uid=root;password=root;database=sncf;persistsecurityinfo=True;allowuservariables=True;keepalive=1;";
			MySql.Data.MySqlClient.MySqlDataAdapter ad2 = null;
			System.Windows.Forms.DataGridViewTextBoxColumn colidbillet = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colidbillet.DataPropertyName = "idbillet";
			colidbillet.HeaderText = "idbillet";
			colidbillet.Name = "colidbillet";
			dataGridView1.Columns.Add(colidbillet);
			System.Windows.Forms.DataGridViewTextBoxColumn colvilleDepart = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colvilleDepart.DataPropertyName = "villeDepart";
			colvilleDepart.HeaderText = "villeDepart";
			colvilleDepart.Name = "colvilleDepart";
			dataGridView1.Columns.Add(colvilleDepart);
			System.Windows.Forms.DataGridViewTextBoxColumn colvilleArrivee = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colvilleArrivee.DataPropertyName = "villeArrivee";
			colvilleArrivee.HeaderText = "villeArrivee";
			colvilleArrivee.Name = "colvilleArrivee";
			dataGridView1.Columns.Add(colvilleArrivee);
			System.Windows.Forms.DataGridViewTextBoxColumn colgareDepart = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colgareDepart.DataPropertyName = "gareDepart";
			colgareDepart.HeaderText = "gareDepart";
			colgareDepart.Name = "colgareDepart";
			dataGridView1.Columns.Add(colgareDepart);
			System.Windows.Forms.DataGridViewTextBoxColumn colgareArrivee = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colgareArrivee.DataPropertyName = "gareArrivee";
			colgareArrivee.HeaderText = "gareArrivee";
			colgareArrivee.Name = "colgareArrivee";
			dataGridView1.Columns.Add(colgareArrivee);
			MyDateTimePickerColumn colheureDepart = new MyDateTimePickerColumn();
			colheureDepart.DataPropertyName = "heureDepart";
			colheureDepart.HeaderText = "heureDepart";
			colheureDepart.Name = "colheureDepart";
			dataGridView1.Columns.Add(colheureDepart);
			MyDateTimePickerColumn colheureArrivee = new MyDateTimePickerColumn();
			colheureArrivee.DataPropertyName = "heureArrivee";
			colheureArrivee.HeaderText = "heureArrivee";
			colheureArrivee.Name = "colheureArrivee";
			dataGridView1.Columns.Add(colheureArrivee);
			System.Windows.Forms.DataGridViewTextBoxColumn colprix = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colprix.DataPropertyName = "prix";
			colprix.HeaderText = "prix";
			colprix.Name = "colprix";
			dataGridView1.Columns.Add(colprix);
			System.Windows.Forms.DataGridViewComboBoxColumn colidtrain = new System.Windows.Forms.DataGridViewComboBoxColumn();
			colidtrain.DataSource = ctx.train.ToList();
			colidtrain.DataPropertyName = "idtrain";
			colidtrain.DisplayMember = "idtrain";
			colidtrain.ValueMember = "idtrain";
			colidtrain.HeaderText = "idtrain";
			colidtrain.Name = "colidtrain";
			colidtrain.ToolTipText = "Pick the column from the foreign table to use as friendly value for this lookup.";
			dataGridView1.Columns.Add(colidtrain);
			System.Windows.Forms.DataGridViewComboBoxColumn colidvoiture = new System.Windows.Forms.DataGridViewComboBoxColumn();
			colidvoiture.DataSource = ctx.voiture.ToList();
			colidvoiture.DataPropertyName = "idvoiture";
			colidvoiture.DisplayMember = "idvoiture";
			colidvoiture.ValueMember = "idvoiture";
			colidvoiture.HeaderText = "idvoiture";
			colidvoiture.Name = "colidvoiture";
			colidvoiture.ToolTipText = "Pick the column from the foreign table to use as friendly value for this lookup.";
			dataGridView1.Columns.Add(colidvoiture);
			System.Windows.Forms.DataGridViewComboBoxColumn colidplace = new System.Windows.Forms.DataGridViewComboBoxColumn();
			colidplace.DataSource = ctx.place.ToList();
			colidplace.DataPropertyName = "idplace";
			colidplace.DisplayMember = "idplace";
			colidplace.ValueMember = "idplace";
			colidplace.HeaderText = "idplace";
			colidplace.Name = "colidplace";
			colidplace.ToolTipText = "Pick the column from the foreign table to use as friendly value for this lookup.";
			dataGridView1.Columns.Add(colidplace);
			System.Windows.Forms.DataGridViewTextBoxColumn colidclient = new System.Windows.Forms.DataGridViewTextBoxColumn();
			colidclient.DataPropertyName = "idclient";
			colidclient.HeaderText = "idclient";
			colidclient.Name = "colidclient";
			dataGridView1.Columns.Add(colidclient);
			dataGridView1.DataSource = _entities;
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			billetBindingSource.EndEdit();
			ctx.SaveChanges();
			
		}
		
		private void frmbillet_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void dataGridView1_CellValidating(object sender, DataGridViewCellValidatingEventArgs e)
		{
			string s;
			DataGridViewRow row = dataGridView1.Rows[e.RowIndex];
			object value = e.FormattedValue;
			e.Cancel = false;
			row.ErrorText = "";
			if (row.IsNewRow) return;
			if (e.ColumnIndex == 0)
			{
				int v;
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field idbillet is required";
					return;
				}
				s = value.ToString();
				if( !int.TryParse( s, out v ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field idbillet must be int.";
					return;
				}
			}
			if (e.ColumnIndex == 1)
			{
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field villeDepart is required";
					return;
				}
			}
			if (e.ColumnIndex == 2)
			{
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field villeArrivee is required";
					return;
				}
			}
			if (e.ColumnIndex == 3)
			{
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field gareDepart is required";
					return;
				}
			}
			if (e.ColumnIndex == 4)
			{
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field gareArrivee is required";
					return;
				}
			}
			if (e.ColumnIndex == 5)
			{
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field heureDepart is required";
					return;
				}
			}
			if (e.ColumnIndex == 6)
			{
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field heureArrivee is required";
					return;
				}
			}
			if (e.ColumnIndex == 7)
			{
				double v;
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field prix is required";
					return;
				}
				s = value.ToString();
				if( !double.TryParse( s, out v ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field prix must be double.";
					return;
				}
			}
			if (e.ColumnIndex == 11)
			{
				int v;
				if( (value is DBNull) || string.IsNullOrEmpty( value.ToString() ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field idclient is required";
					return;
				}
				s = value.ToString();
				if( !int.TryParse( s, out v ) )
				{
					e.Cancel = true;
					row.ErrorText = "The field idclient must be int.";
					return;
				}
			}
		}
		
		private void dataGridView1_DataError(object sender, DataGridViewDataErrorEventArgs e)
		{
			dataGridView1.Rows[e.RowIndex].ErrorText = e.Exception.Message;
			e.Cancel = true;
		}
		
		
		
		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			billetBindingSource.AddNew();
		}
	}
}
